// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShortURL is a mock of ShortURL interface.
type MockShortURL struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLMockRecorder
	isgomock struct{}
}

// MockShortURLMockRecorder is the mock recorder for MockShortURL.
type MockShortURLMockRecorder struct {
	mock *MockShortURL
}

// NewMockShortURL creates a new mock instance.
func NewMockShortURL(ctrl *gomock.Controller) *MockShortURL {
	mock := &MockShortURL{ctrl: ctrl}
	mock.recorder = &MockShortURLMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURL) EXPECT() *MockShortURLMockRecorder {
	return m.recorder
}

// FormatShortURL mocks base method.
func (m *MockShortURL) FormatShortURL(baseURL, urlID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FormatShortURL", baseURL, urlID)
	ret0, _ := ret[0].(string)
	return ret0
}

// FormatShortURL indicates an expected call of FormatShortURL.
func (mr *MockShortURLMockRecorder) FormatShortURL(baseURL, urlID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FormatShortURL", reflect.TypeOf((*MockShortURL)(nil).FormatShortURL), baseURL, urlID)
}

// GetOriginal mocks base method.
func (m *MockShortURL) GetOriginal(slug string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginal", slug)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOriginal indicates an expected call of GetOriginal.
func (mr *MockShortURLMockRecorder) GetOriginal(slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginal", reflect.TypeOf((*MockShortURL)(nil).GetOriginal), slug)
}

// Shorten mocks base method.
func (m *MockShortURL) Shorten(url string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shorten", url)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shorten indicates an expected call of Shorten.
func (mr *MockShortURLMockRecorder) Shorten(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shorten", reflect.TypeOf((*MockShortURL)(nil).Shorten), url)
}

// MockShortURLRepo is a mock of ShortURLRepo interface.
type MockShortURLRepo struct {
	ctrl     *gomock.Controller
	recorder *MockShortURLRepoMockRecorder
	isgomock struct{}
}

// MockShortURLRepoMockRecorder is the mock recorder for MockShortURLRepo.
type MockShortURLRepoMockRecorder struct {
	mock *MockShortURLRepo
}

// NewMockShortURLRepo creates a new mock instance.
func NewMockShortURLRepo(ctrl *gomock.Controller) *MockShortURLRepo {
	mock := &MockShortURLRepo{ctrl: ctrl}
	mock.recorder = &MockShortURLRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortURLRepo) EXPECT() *MockShortURLRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockShortURLRepo) Get(slug string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", slug)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockShortURLRepoMockRecorder) Get(slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockShortURLRepo)(nil).Get), slug)
}

// Save mocks base method.
func (m *MockShortURLRepo) Save(slug, url string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", slug, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockShortURLRepoMockRecorder) Save(slug, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockShortURLRepo)(nil).Save), slug, url)
}
